var episodeType = ["resourceType" ,"combatType", "medicalType" , "scienceType", "respiteType"]; //add

var resourceType = {problemTitle:["Space Resources"],
    originPlot:{problemPicture: "alientrader.jpg", problemAttribute: [10,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [0] ,problemDescription: ["randomName", " is an alien " , "randomJob" , " from the " , "randomRace" , " race.  He offers your crew the coordinates of a rare " , "randomItem", " which could greatly improve your ships warp speed.  However, he says he is only willing to negotiate with " , "firstMateName" , ". As captain your concerned about the risk to your crew."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure"], problemAnswer:[["number 1", "captainName"], "choose this one","","",""]},
    plotTwistOne:{problemPicture: "sickbayone.jpg", problemAttribute: [11,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [-15,"speedAttribute"] ,problemDescription: ["randomItem", "s.... 'we need em!"], resultPossitive:"You have the space dust!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure" ,"winner"], failureText:"bummer", problemAnswer:[["passivo: 'who cares!' blurts out captain ", "captainName"], "neutralo","aggressivo", "choose this one",""]},
    plotTwistTwo:{problemPicture: "allcrew.jpg", problemAttribute: [12,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [15,"shieldAttribute"] ,problemDescription: ["The " ,"randomItem","! I must have it."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["choose this one", "neutralo","aggressivo","",""]},
    failure:{problemPicture: "shipexplosion.jpg", problemAttribute: [13,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [-15,"weaponAttribute"] ,problemDescription: ["Your ship has blown up."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["End game.","","","",""]},
    winner:{problemPicture: "earth.jpg", problemAttribute: [14,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [15,"firstMateAttribute"] ,problemDescription: ["Awesome!"], resultPossitive:"winner!", resultNegative:["originPlot", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:["Continue","","","",""]}
};

var combatType = {problemTitle:["You discover a new alien."],
    originPlot:{problemPicture: "alientrader.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [-20,"speedAttribute"] ,problemDescription: ["randomName", " is an alien " , "randomJob" , " from the " , "randomRace" , " race.  He offers your crew the coordinates of a rare " , "randomItem", " which could greatly improve your ships warp speed.  However, he says he is only willing to negotiate with " , "firstMateName" , ". As captain your concerned about the risk to your crew."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:[["number 1", "captainName"], "choose this one","","",""]},
    plotTwistOne:{problemPicture: "sickbayone.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [20,"speedAttribute"] ,problemDescription: ["randomItem", "s.... 'we need em!"], resultPossitive:"You have the space dust!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:[["passivo: 'who cares!' blurts out captain ", "captainName"], "neutralo","aggressivo", "choose this one",""]},
    plotTwistTwo:{problemPicture: "allcrew.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [-20,"shieldAttribute"] ,problemDescription: ["The " ,"randomItem","! I must have it."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["choose this one", "neutralo","aggressivo","",""]},
    failure:{problemPicture: "shipexplosion.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [20,"shieldAttribute"] ,problemDescription: ["Your ship has blown up."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["End game.","","","",""]},
    winner:{problemPicture: "earth.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10,"shieldAttribute"] ,problemDescription: ["Awesome!"], resultPossitive:"winner!", resultNegative:["originPlot", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:["Continue","","","",""]}
};

var medicalType = {problemTitle:["Medical Emergency!"],
    originPlot:{problemPicture: "alientrader.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [-10,"speedAttribute"] ,problemDescription: ["randomName" , ", a seemingly altruistic and powerful alien, has made it his job to take care of a pre-warp civilization. From his perch 'on high,' his orbiting ", "randomMadeObject", " is shielding the planet below from all threats, but also preventing the civilization from advancing. Spacefleet would not approve of this tampering with a civilizations normal evolution. The alien's technology might be powerful enough to get you home quickly; If you could get a hold of it one way or another..."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:[["number 1", "captainName"], "choose this one","","",""]},
    plotTwistOne:{problemPicture: "sickbayone.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10, "speedAttribute"] ,problemDescription: ["randomItem", "s.... 'we need em!"], resultPossitive:"You have the space dust!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:[["passivo: 'who cares!' blurts out captain ", "captainName"], "neutralo","aggressivo", "choose this one",""]},
    plotTwistTwo:{problemPicture: "allcrew.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10,"shieldAttribute"] ,problemDescription: ["The " ,"randomItem","! I must have it."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["choose this one", "neutralo","aggressivo","",""]},
    failure:{problemPicture: "shipexplosion.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [-10, "shieldAttribute"] ,problemDescription: ["Your ship has blown up."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["End game.","","","",""]},
    winner:{problemPicture: "earth.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10,"shieldAttribute"] ,problemDescription: ["Awesome!"], resultPossitive:"winner!", resultNegative:["originPlot", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:["Continue","","","",""]}
};


var scienceType = {problemTitle:["Ooooo! a flyiing rock..."],
    originPlot:{problemPicture: "alientrader.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10,"speedAttribute"] ,problemDescription: ["randomName", " is an alien " , "randomJob" , " from the " , "randomRace" , " race.  He offers your crew the coordinates of a rare " , "randomItem", " which could greatly improve your ships warp speed.  However, he says he is only willing to negotiate with " , "firstMateName" , ". As captain your concerned about the risk to your crew."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:[["number 1", "captainName"], "choose this one","","",""]},
    plotTwistOne:{problemPicture: "sickbayone.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [-10, "speedAttribute"] ,problemDescription: ["randomItem", "s.... 'we need em!"], resultPossitive:"You have the space dust!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:[["passivo: 'who cares!' blurts out captain ", "captainName"], "neutralo","aggressivo", "choose this one",""]},
    plotTwistTwo:{problemPicture: "allcrew.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10, "shieldAttribute"] ,problemDescription: ["The " ,"randomItem","! I must have it."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["choose this one", "neutralo","aggressivo","",""]},
    failure:{problemPicture: "shipexplosion.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [-10, "shieldAttribute"] ,problemDescription: ["Your ship has blown up."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["End game.","","","",""]},
    winner:{problemPicture: "earth.jpg", problemAttribute: [1,"speedAttribute" , "firstMateAttribute"] , immediateAttribute: [10,"shieldAttribute"] ,problemDescription: ["Awesome!"], resultPossitive:"winner!", resultNegative:["originPlot", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:["Continue","","","",""]}
};

var respiteType = {problemTitle:["Repairs"],
    originPlot:{problemPicture: "alientrader.jpg", problemAttribute: [10,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [0] ,problemDescription: ["randomName", " is an alien " , "randomJob" , " from the " , "randomRace" , " race.  He offers your crew the coordinates of a rare " , "randomItem", " which could greatly improve your ships warp speed.  However, he says he is only willing to negotiate with " , "firstMateName" , ". As captain your concerned about the risk to your crew."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure"], problemAnswer:[["number 1", "captainName"], "choose this one","","",""]},
    plotTwistOne:{problemPicture: "sickbayone.jpg", problemAttribute: [11,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [-15,"speedAttribute"] ,problemDescription: ["randomItem", "s.... 'we need em!"], resultPossitive:"You have the space dust!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure" ,"winner"], failureText:"bummer", failureText:"bummer", problemAnswer:[["passivo: 'who cares!' blurts out captain ", "captainName"], "neutralo","aggressivo", "choose this one",""]},
    plotTwistTwo:{problemPicture: "allcrew.jpg", problemAttribute: [12,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [15,"shieldAttribute"] ,problemDescription: ["The " ,"randomItem","! I must have it."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["choose this one", "neutralo","aggressivo","",""]},
    failure:{problemPicture: "shipexplosion.jpg", problemAttribute: [13,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [-15,"weaponAttribute"] ,problemDescription: ["Your ship has blown up."], resultPossitive:"You have the crystal!", resultNegative:["plotTwistOne", "plotTwistTwo", "plotTwistOne", "failure","winner"], failureText:"bummer", problemAnswer:["End game.","","","",""]},
    winner:{problemPicture: "earth.jpg", problemAttribute: [14,"resourceAttribute" , "firstMateAttribute"] , immediateAttribute: [15,"firstMateAttribute"] ,problemDescription: ["Awesome!"], resultPossitive:"winner!", resultNegative:["originPlot", "plotTwistTwo", "plotTwistOne", "failure","winner"], problemAnswer:["Continue","","","",""]}
};

var totalObjectType = ["randomName" , "randomMadeObject" , "randomItem","shipName","captainName","firstMateName" , "randomJob","randomRace"]; //this has to be manually set to reflect all the var objects below it.
var randomName =["Ardwin", "Batok", "Catarin" , "Dour-gin"];
var randomMadeObject =["spaceship", "spacestation" , "colony"];
var randomItem = ["crystal" ,"warp conduit"];
var randomJob = ["trader" , "janitor" ,"ambasidor"];
var randomRace = ["Panuk", "Hilaari", "Upchu"];

var shipName = "USS Treker";
var captainName = "Juneway";
var firstMateName = "Albert";
var securityName ="";
var medicalName ="";
var chiefName ="";

function setUserChoice(){
    shipName = document.getElementById("shipChoice").value;
    captainName = document.getElementById("captainChoice").value;
    speedOrigin = document.getElementById("speedChoice").value;
    saveLocal();

    console.log(shipName);
}
